server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    static-path-pattern: /static/**
    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://burgerking.cl6j84vpzotz.ap-northeast-2.rds.amazonaws.com/burgerking?useUnicode=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: gyeongun
    password: qwer1234
  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:        registration:          naver:
            client-id: dMoKqwAkVeHRQTbuhg43
            client-secret: 3MVHzfpIMS
            scope:            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirectUri: http://localhost:8000/login/oauth2/code/naver
          kakao:
            client-id: 55ee8e287972612398f2e5eafef1ac93
            scope:
            - account_email
            - profile_nickname
            - profile_image
            client-authentication-method: POST
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  web:
    resources:
      static-locations:
      - classpath:/static/
      add-mappings: true
mybatis:
  mapper-locations:
  - /mappers/*.xml

